# Nombre de la pipeline
name: Pipeline de Pruebas Serenity Selenium

# Triggers para iniciar la pipeline al hacer push al repositorio
trigger:
  batch: true
  branches:
    include:
    - main
    
# Variables para la configuración
variables:
  mavenPomFile: 'pom.xml'
  testResultsDirectory: '$(System.DefaultWorkingDirectory)/target/site/serenity'
  codeCoverageTool: 'Cobertura'
  codeCoverageReportFile: '$(System.DefaultWorkingDirectory)/target/site/cobertura/coverage.xml'

stages:
  - stage:
    displayName: 'STAGE: Execute Functional Test'
    jobs:
      - job:
      
        displayName: 'JOB: Execute Functional Test' # friendly name to display in the UI
        workspace:
          clean: all
        
        steps:
        - task: Maven@1
          displayName: Maven Compile
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
          

        - task: Maven@3
          displayName: Maven clean verify
          continueOnError: true
          timeoutInMinutes: 20
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify'
            options: '-Dwebdriver.chrome.driver=$(webDriver) '
            #options: '-Dwebdriver.chrome.driver=$(System.DefaultWorkingDirectory)/src/test/resources/webdriver/linux/chromedriver'
            # -Dtags=@ValidLogin'
            publishJUnitResults: false
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenOptions: '-Xmx3072m'
            jdkArchitectureOption: 'x64'
            jdkVersionOption: '1.8'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
          

